store/products/urls.py
from django.urls import path
from pr
from products.views import products,basket_add,basket_delete

app_name = 'products'

urlpatterns = [
   path('',products,name='index'),
   path('<int:category_id>/', products, name='category'),
   path('page/<int:page>/', products, name='page'),
   path('basket-add/<int:product_id>/',basket_add,name='basket_add'),
   path('basket_delete/<int:id>/', basket_delete, name='basket_delete'),

]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from products.
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/',include('products.urls',namespace='products')),
    path('users/',include('users.urls',namespace='users')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/users/urls.py
from django.urls import path
from users.views import login, register,profile,logout

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('profile/',profile,name='profile'),
    path('logout/',logout,name='logout')
]

store/products/models.py
from django.db import models
from users.models import User

# Create your models here.

class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'ProductCategories'


    def __str__(self):
        return self.name




class Product(models.Model):
    name = models.CharField(max_length=256)
    image = models.ImageField(upload_to='products_images', blank=True)
    description = models.TextField(blank=True)
    short_description = models.CharField(max_length=64, blank=True)
    price = models.DecimalField(max_digits=4,decimal_places=0, default=0)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductCategory,on_delete=models.CASCADE)

    def __str__(self):
        return self.name + ' | ' + self.category.name


class Basket(models.Model):
    user =models.ForeignKey(User,on_delete=models.CASCADE)

    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return 'Корзина для:' + self.user.username + '|' + self.product.name

    def sum(self):
        return self.quantity * self.product.price

store/products/views.py
from django.shortcuts import render, HttpResponseRedirect
from products.models import Product, ProductCategory, Basket
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator


# Create your views here.


def index(request):
    context = {
        'title': 'BelStore'
    }
    return render(request, 'products/index.html', context)


def products(request, category_id=None,page=1):

    context = {
        'title': 'Каталог',
        'categories': ProductCategory.objects.all()
    }
    if category_id:
        products = Product.objects.filter(category_id=category_id)
    else:
       products = Product.objects.all()
    paginator =Paginator(products, 3)
    products_paginator = paginator.page(page)
    context.update({'products':products_paginator})
    return render(request, 'products/products.html', context)


@login_required
def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():

        Basket.objects.create(user=request.user, product=product, quantity=1)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_delete(request, id):
    basket = Basket.objects.get(id=id)
    basket.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

store/products/templates/products/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title|title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
  {% block css %} {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">BelStore</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог<i class="fas fa-shopping-bag"></i> </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:profile' %}">{{ user.username }}
                        <i class="fas fa-user-circle"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Выйти <i class="fas fa-sign-out-alt"></i></a>
                </li>
                {% else %}
                     <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                </li>
                {% endif %}


            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %}  {% endblock %}

{% block footer %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

store/products/templates/products/basket.html
{% if baskets %}
    <div class="col-lg-5">
            <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
                Корзина <span class="badge badge-secondary badge-pill">{{ total_quantity }}</span>
            </h4>
        {% for basket in baskets %}
              <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ basket.product.name }}</h5>
                    <p class="card-text">{{   basket.product.short_description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item d-flex justify-content-between lh-condensed bg-light ">
                        <span class="text-muted">{{ basket.quantity }} шт.</span>
                        <span class="text-muted">{{ basket.sum }}$</span>
                        <span class="text-muted"></span>
                        <a href="{% url 'products:basket_add' basket.product.id %}">

                            <button>добавить</button>
                        </a>
                        <a href="{% url 'products:basket_delete' basket.id %}">

                            <button>удалить</button>
                        </a>

                    </li>
                </ul>
            </div>
        {% endfor %}

            <div class="card mb-3">
                <div class="card-footer">
                    <p class="float-left">Итого</p>
                    <h4 class="float-right">{{ total_sum}}$</h4>
                </div>
            </div>
            <a class="btn btn-success btn-lg float-right" href="../orders/order-create.html">
                Оформить заказ
            </a>
        </div>
{% else %}
      <h4 class="mt-3 mb-3  text-center ">
                Корзина пуста
            </h4>
{% endif %}

store/products/templates/products/index.html
{% extends 'products/base.html' %}
{% load staticfiles %}
{% block css %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <section>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">BelStore</h1>
                <p>
                    Новые образы и лучшие бренды BelStore.
                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'products:index' %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock %}

store/products/templates/products/products.html
{% extends 'products/base.html' %}
{%  load staticfiles %}

{% block css %}
 <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Store</h1>
            <div class="list-group">

                {% for category in categories %}
                <a href="{% url 'products:category' category.id %}"
                   class="list-group-item">{{ category.name }}</a>
                {% endfor %}
            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-1.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-2.jpg" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-3.jpg" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">

                {%  for product in products %}
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                                 src="/media/{{ product.image }}"
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">{{ product.name }}</a>
                            </h4>
                            <h5>{{ product.price }}$</h5>
                            <p class="card-text">{{ product.short_description }}</p>
                        </div>
                        <div class="card-footer text-center">
                            <a href="{% url 'products:basket_add' product.id %}"><button type="button" class="btn btn-outline-success">Отправить в корзину</button></a>

                        </div>
                    </div>
                </div>
                {% endfor %}


            </div>

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item  {% if not products.has_previous %} disabled{% endif %}">
                        <a class="page-link"
                           href="{% if products.has_previous %} {% url 'products:page' products.previous_page_number %} {% else %} # {% endif %}"
                           tabindex="-1" aria-disabled="true">Previous</a>
                    </li>
                {% for page in products.paginator.page_range %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'products:page' page %}">
                            {{ page }}
                        </a>
                    </li>
                {% endfor %}

                    <li class="page-item {% if not products.has_next %} disabled{% endif %}">
                        <a class="page-link"
                           href="{% if products.has_next %} {% url 'products:page' products.next_page_number %} {% else %} #{% endif %}"
                        >Next</a>
                    </li>
                </ul>
            </nav>

        </div>

    </div>

</div>
{% endblock %}
{% block footer %}
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Store 2021</p>
    </div>
    <!-- /.container -->
</footer>
{% endblock %}